### PR TITLE
finished many to many relationship

### PR DESCRIPTION
**Pull request by Tonyynot14**
Many to many relationship of players to games

### CODE REVIEW

**Comment by Tonyynot14** [comment]
having issues with the rails application assuming I want to use the default destroy method and not the specific method like remove players. only works when remove players route is the top of the routes file

**Comment by jrmcgarvey** [comment]
Looks good to me

**Comment by Tonyynot14** [comment]
reading what you said made me thing of a idea and i figured it out. I changed the route from plural to singular and now it works anywhere in the routes.

**Comment by Tonyynot14** [comment]
Changed routes for deleting records in combined table to being singular instead of plural so that they would not conflict in resolution of routes

**Pull request merged**
